/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PLAYER2_RPC_H_RPCGEN
#define _PLAYER2_RPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


#define PLAYER2PROG 0x3FFFFFFF
#define PLAYER2VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define LAUNCHBALLP2 1
extern  enum clnt_stat launchballp2_1(void *, int *, CLIENT *);
extern  bool_t launchballp2_1_svc(void *, int *, struct svc_req *);
#define GETRACK2 2
extern  enum clnt_stat getrack2_1(int *, int *, CLIENT *);
extern  bool_t getrack2_1_svc(int *, int *, struct svc_req *);
extern int player2prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LAUNCHBALLP2 1
extern  enum clnt_stat launchballp2_1();
extern  bool_t launchballp2_1_svc();
#define GETRACK2 2
extern  enum clnt_stat getrack2_1();
extern  bool_t getrack2_1_svc();
extern int player2prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PLAYER2_RPC_H_RPCGEN */

