/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "player1_rpc.h"
#include "game.h"
#include "moveball.h"

extern SDL_TimerID timer;
extern PPong_Game game;

bool_t
launchballp1_1_svc(void *argp, int *result, struct svc_req *rqstp)
{
  bool_t retval;

  SDL_RemoveTimer(timer);

  timer = SDL_AddTimer(BSPEED, MoveBall, &game);

    if(timer)
        retval = 1;
    else
        retval = 0;

  return retval;
}

int
player1prog_1_freeresult (SVCXPRT *transp, xdrproc_t xdr_result, caddr_t result)
{
	xdr_free (xdr_result, result);

	/*
	 * Insert additional freeing code here, if needed
	 */

	return 1;
}
