/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PLAYER1_RPC_H_RPCGEN
#define _PLAYER1_RPC_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


#define PLAYER1PROG 0x3FFFFFFE
#define PLAYER1VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define LAUNCHBALLP1 1
extern  enum clnt_stat launchballp1_1(void *, int *, CLIENT *);
extern  bool_t launchballp1_1_svc(void *, int *, struct svc_req *);
extern int player1prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define LAUNCHBALLP1 1
extern  enum clnt_stat launchballp1_1();
extern  bool_t launchballp1_1_svc();
extern int player1prog_1_freeresult ();
#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PLAYER1_RPC_H_RPCGEN */
